table retail_sales_monthly

	measure 'Retail Sales CAD' =
			SUM ( retail_sales_monthly[sales_cad_thousands] ) * 1000
		formatString: "#,0"

	measure 'Selected Month' =
			COALESCE ( SELECTEDVALUE ( 'Report Month'[month] ), CALCULATE ( MAX ( retail_sales_monthly[month] ), REMOVEFILTERS ( retail_sales_monthly ) ) )
		formatString: "mmm yyyy"

	measure 'Edmonton Sales CAD' =
			VAR TargetMonth = COALESCE ( SELECTEDVALUE ( 'Report Month'[month] ), CALCULATE ( MAX ( retail_sales_monthly[month] ), REMOVEFILTERS ( retail_sales_monthly ) ) )
			RETURN
			    CALCULATE ( SUM ( retail_sales_monthly[sales_cad_thousands] ) * 1000, REMOVEFILTERS ( retail_sales_monthly ), retail_sales_monthly[month] = TargetMonth, retail_sales_monthly[geography] = "Edmonton, Alberta" )
		formatString: "#,0"

	measure 'Calgary Sales CAD' =
			VAR TargetMonth = COALESCE ( SELECTEDVALUE ( 'Report Month'[month] ), CALCULATE ( MAX ( retail_sales_monthly[month] ), REMOVEFILTERS ( retail_sales_monthly ) ) )
			RETURN
			    CALCULATE ( SUM ( retail_sales_monthly[sales_cad_thousands] ) * 1000, REMOVEFILTERS ( retail_sales_monthly ), retail_sales_monthly[month] = TargetMonth, retail_sales_monthly[geography] = "Calgary, Alberta" )
		formatString: "#,0"

	measure 'Alberta Sales CAD' =
			VAR TargetMonth = COALESCE ( SELECTEDVALUE ( 'Report Month'[month] ), CALCULATE ( MAX ( retail_sales_monthly[month] ), REMOVEFILTERS ( retail_sales_monthly ) ) )
			RETURN
			    CALCULATE ( SUM ( retail_sales_monthly[sales_cad_thousands] ) * 1000, REMOVEFILTERS ( retail_sales_monthly ), retail_sales_monthly[month] = TargetMonth, retail_sales_monthly[geography] = "Alberta" )
		formatString: "#,0"

	measure 'Edmonton Sales Last Year CAD' =
			VAR PriorYearMonth = EDATE ( COALESCE ( SELECTEDVALUE ( 'Report Month'[month] ), CALCULATE ( MAX ( retail_sales_monthly[month] ), REMOVEFILTERS ( retail_sales_monthly ) ) ), -12 )
			RETURN
			    CALCULATE ( SUM ( retail_sales_monthly[sales_cad_thousands] ) * 1000, REMOVEFILTERS ( retail_sales_monthly ), retail_sales_monthly[month] = PriorYearMonth, retail_sales_monthly[geography] = "Edmonton, Alberta" )
		formatString: "#,0"

	measure 'Calgary Sales Last Year CAD' =
			VAR PriorYearMonth = EDATE ( COALESCE ( SELECTEDVALUE ( 'Report Month'[month] ), CALCULATE ( MAX ( retail_sales_monthly[month] ), REMOVEFILTERS ( retail_sales_monthly ) ) ), -12 )
			RETURN
			    CALCULATE ( SUM ( retail_sales_monthly[sales_cad_thousands] ) * 1000, REMOVEFILTERS ( retail_sales_monthly ), retail_sales_monthly[month] = PriorYearMonth, retail_sales_monthly[geography] = "Calgary, Alberta" )
		formatString: "#,0"

	measure 'Edmonton YoY %' =
			VAR TargetMonth = COALESCE ( SELECTEDVALUE ( 'Report Month'[month] ), CALCULATE ( MAX ( retail_sales_monthly[month] ), REMOVEFILTERS ( retail_sales_monthly ) ) )
			VAR PriorYearMonth = EDATE ( TargetMonth, -12 )
			VAR CurrentSales = CALCULATE ( SUM ( retail_sales_monthly[sales_cad_thousands] ) * 1000, REMOVEFILTERS ( retail_sales_monthly ), retail_sales_monthly[month] = TargetMonth, retail_sales_monthly[geography] = "Edmonton, Alberta" )
			VAR PriorYearSales = CALCULATE ( SUM ( retail_sales_monthly[sales_cad_thousands] ) * 1000, REMOVEFILTERS ( retail_sales_monthly ), retail_sales_monthly[month] = PriorYearMonth, retail_sales_monthly[geography] = "Edmonton, Alberta" )
			RETURN
			    DIVIDE ( CurrentSales - PriorYearSales, PriorYearSales )
		formatString: "0.00%;-0.00%;0.00%"

	measure 'Calgary YoY %' =
			VAR TargetMonth = COALESCE ( SELECTEDVALUE ( 'Report Month'[month] ), CALCULATE ( MAX ( retail_sales_monthly[month] ), REMOVEFILTERS ( retail_sales_monthly ) ) )
			VAR PriorYearMonth = EDATE ( TargetMonth, -12 )
			VAR CurrentSales = CALCULATE ( SUM ( retail_sales_monthly[sales_cad_thousands] ) * 1000, REMOVEFILTERS ( retail_sales_monthly ), retail_sales_monthly[month] = TargetMonth, retail_sales_monthly[geography] = "Calgary, Alberta" )
			VAR PriorYearSales = CALCULATE ( SUM ( retail_sales_monthly[sales_cad_thousands] ) * 1000, REMOVEFILTERS ( retail_sales_monthly ), retail_sales_monthly[month] = PriorYearMonth, retail_sales_monthly[geography] = "Calgary, Alberta" )
			RETURN
			    DIVIDE ( CurrentSales - PriorYearSales, PriorYearSales )
		formatString: "0.00%;-0.00%;0.00%"

	measure 'Edmonton Share of Alberta %' =
			VAR TargetMonth = COALESCE ( SELECTEDVALUE ( 'Report Month'[month] ), CALCULATE ( MAX ( retail_sales_monthly[month] ), REMOVEFILTERS ( retail_sales_monthly ) ) )
			VAR EdmontonSales = CALCULATE ( SUM ( retail_sales_monthly[sales_cad_thousands] ) * 1000, REMOVEFILTERS ( retail_sales_monthly ), retail_sales_monthly[month] = TargetMonth, retail_sales_monthly[geography] = "Edmonton, Alberta" )
			VAR AlbertaSales = CALCULATE ( SUM ( retail_sales_monthly[sales_cad_thousands] ) * 1000, REMOVEFILTERS ( retail_sales_monthly ), retail_sales_monthly[month] = TargetMonth, retail_sales_monthly[geography] = "Alberta" )
			RETURN
			    DIVIDE ( EdmontonSales, AlbertaSales )
		formatString: "0.00%;-0.00%;0.00%"

	measure 'Trend YoY %' =
			VAR AxisMonth = SELECTEDVALUE ( retail_sales_monthly[month] )
			VAR CurrentSales = SUM ( retail_sales_monthly[sales_cad_thousands] ) * 1000
			VAR PriorYearSales =
			    CALCULATE (
			        SUM ( retail_sales_monthly[sales_cad_thousands] ) * 1000,
			        REMOVEFILTERS ( retail_sales_monthly[month] ),
			        retail_sales_monthly[month] = EDATE ( AxisMonth, -12 )
			    )
			RETURN
			    IF ( NOT ISBLANK ( AxisMonth ), DIVIDE ( CurrentSales - PriorYearSales, PriorYearSales ) )
		formatString: "0.00%;-0.00%;0.00%"

	/// Sales for the selected report month; preserves the geography on the chart axis.
	measure 'Selected Month Sales CAD' =
			VAR TargetMonth = COALESCE ( SELECTEDVALUE ( 'Report Month'[month] ), CALCULATE ( MAX ( retail_sales_monthly[month] ), REMOVEFILTERS ( retail_sales_monthly ) ) )
			RETURN
			    CALCULATE ( SUM ( retail_sales_monthly[sales_cad_thousands] ) * 1000, retail_sales_monthly[month] = TargetMonth )
		formatString: "#,0"


	column month
		dataType: dateTime
		formatString: "mmm yyyy"
		summarizeBy: none
		sourceColumn: month
		annotation UnderlyingDateTimeDataType = Date

	column geography
		dataType: string
		summarizeBy: none
		sourceColumn: geography

	column sales_cad_thousands
		dataType: int64
		formatString: "#,0"
		summarizeBy: none
		sourceColumn: sales_cad_thousands

	column quality_status
		dataType: string
		summarizeBy: none
		sourceColumn: quality_status


	partition retail_sales_monthly = m
		mode: import
		source =
			let
			    Source = Csv.Document(Binary.FromText("bW9udGgsZ2VvZ3JhcGh5LHNhbGVzX2NhZF90aG91c2FuZHMscXVhbGl0eV9zdGF0dXMNCjIwMjMtMDEsIkVkbW9udG9uLCBBbGJlcnRhIiwyNTQzMjEwLEENCjIwMjMtMDEsIkNhbGdhcnksIEFsYmVydGEiLDI0MjUzMjEsQQ0KMjAyMy0wMSxBbGJlcnRhLDc0MjI2NDAsQQ0KMjAyMy0wMSxDYW5hZGEsNTUxNjMzNjEsQQ0KMjAyMy0wMiwiRWRtb250b24sIEFsYmVydGEiLDI0ODQ1MDUsQQ0KMjAyMy0wMiwiQ2FsZ2FyeSwgQWxiZXJ0YSIsMjQwODQxNCxBDQoyMDIzLTAyLEFsYmVydGEsNzIxOTQ3OSxBDQoyMDIzLTAyLENhbmFkYSw1MzcxODQyNCxBDQoyMDIzLTAzLCJFZG1vbnRvbiwgQWxiZXJ0YSIsMjk3MDk2MCxBDQoyMDIzLTAzLCJDYWxnYXJ5LCBBbGJlcnRhIiwyODMzMDM4LEENCjIwMjMtMDMsQWxiZXJ0YSw4NTE0NTU4LEENCjIwMjMtMDMsQ2FuYWRhLDY0NTAxMDk2LEENCjIwMjMtMDQsIkVkbW9udG9uLCBBbGJlcnRhIiwyNzg5OTMzLEENCjIwMjMtMDQsIkNhbGdhcnksIEFsYmVydGEiLDI3MjA4NDMsQQ0KMjAyMy0wNCxBbGJlcnRhLDgyNTY0OTksQQ0KMjAyMy0wNCxDYW5hZGEsNjQ4MzgzNjksQQ0KMjAyMy0wNSwiRWRtb250b24sIEFsYmVydGEiLDMyMTk5NTAsQQ0KMjAyMy0wNSwiQ2FsZ2FyeSwgQWxiZXJ0YSIsMzE2Mzk3OCxBDQoyMDIzLTA1LEFsYmVydGEsOTUyMjIzOCxBDQoyMDIzLTA1LENhbmFkYSw3MjQ2NTMyOSxBDQoyMDIzLTA2LCJFZG1vbnRvbiwgQWxiZXJ0YSIsMzA3OTM2NyxBDQoyMDIzLTA2LCJDYWxnYXJ5LCBBbGJlcnRhIiwyOTg5OTE2LEENCjIwMjMtMDYsQWxiZXJ0YSw5MTE4OTgxLEENCjIwMjMtMDYsQ2FuYWRhLDcwODYzNDEyLEENCjIwMjMtMDcsIkVkbW9udG9uLCBBbGJlcnRhIiwyOTYyNTgyLEENCjIwMjMtMDcsIkNhbGdhcnksIEFsYmVydGEiLDI2OTcyMzIsQQ0KMjAyMy0wNyxBbGJlcnRhLDg1NTYxNTcsQQ0KMjAyMy0wNyxDYW5hZGEsNjgxMjQ4NjUsQQ0KMjAyMy0wOCwiRWRtb250b24sIEFsYmVydGEiLDMwNjA1NjMsQQ0KMjAyMy0wOCwiQ2FsZ2FyeSwgQWxiZXJ0YSIsMjgyMTkyNyxBDQoyMDIzLTA4LEFsYmVydGEsODk0MDM2NixBDQoyMDIzLTA4LENhbmFkYSw2OTQ4NzA5MixBDQoyMDIzLTA5LCJFZG1vbnRvbiwgQWxiZXJ0YSIsMjg5NDA2NCxBDQoyMDIzLTA5LCJDYWxnYXJ5LCBBbGJlcnRhIiwyNjkxOTUzLEENCjIwMjMtMDksQWxiZXJ0YSw4NDg1MzYyLEENCjIwMjMtMDksQ2FuYWRhLDY3MTc5MjQwLEENCjIwMjMtMTAsIkVkbW9udG9uLCBBbGJlcnRhIiwyOTE4MjM3LEENCjIwMjMtMTAsIkNhbGdhcnksIEFsYmVydGEiLDI4MDMzOTUsQQ0KMjAyMy0xMCxBbGJlcnRhLDg2Nzg2MDksQQ0KMjAyMy0xMCxDYW5hZGEsNjc2NzU0NzYsQQ0KMjAyMy0xMSwiRWRtb250b24sIEFsYmVydGEiLDI4OTE1NTEsQQ0KMjAyMy0xMSwiQ2FsZ2FyeSwgQWxiZXJ0YSIsMjc5MjU3NSxBDQoyMDIzLTExLEFsYmVydGEsODU2MDU5NixBDQoyMDIzLTExLENhbmFkYSw2OTI0Mjg3NixBDQoyMDIzLTEyLCJFZG1vbnRvbiwgQWxiZXJ0YSIsMzAyNjQ5NixBDQoyMDIzLTEyLCJDYWxnYXJ5LCBBbGJlcnRhIiwyODE5MzI5LEENCjIwMjMtMTIsQWxiZXJ0YSw4NzAzNjEwLEENCjIwMjMtMTIsQ2FuYWRhLDY5MTA5NTE4LEENCjIwMjQtMDEsIkVkbW9udG9uLCBBbGJlcnRhIiwyNDg4MTE1LEENCjIwMjQtMDEsIkNhbGdhcnksIEFsYmVydGEiLDIzMTIwMzAsQQ0KMjAyNC0wMSxBbGJlcnRhLDcyMDM5NzMsQQ0KMjAyNC0wMSxDYW5hZGEsNTY3OTU0MTEsQQ0KMjAyNC0wMiwiRWRtb250b24sIEFsYmVydGEiLDI1NDIwNDIsQQ0KMjAyNC0wMiwiQ2FsZ2FyeSwgQWxiZXJ0YSIsMjM0NTc1NSxBDQoyMDI0LTAyLEFsYmVydGEsNzI2MzIyNSxBDQoyMDI0LTAyLENhbmFkYSw1NzQwMTQ1MixBDQoyMDI0LTAzLCJFZG1vbnRvbiwgQWxiZXJ0YSIsMjk0NTE2NixBDQoyMDI0LTAzLCJDYWxnYXJ5LCBBbGJlcnRhIiwyNTk3ODk4LEENCjIwMjQtMDMsQWxiZXJ0YSw4MjEzMzI3LEENCjIwMjQtMDMsQ2FuYWRhLDY0MDQ3MTA0LEENCjIwMjQtMDQsIkVkbW9udG9uLCBBbGJlcnRhIiwzMDQ0MDQzLEENCjIwMjQtMDQsIkNhbGdhcnksIEFsYmVydGEiLDI3NzEzMzksQQ0KMjAyNC0wNCxBbGJlcnRhLDg2NjQwNzksQQ0KMjAyNC0wNCxDYW5hZGEsNjc1NzY3MzQsQQ0KMjAyNC0wNSwiRWRtb250b24sIEFsYmVydGEiLDMyNjU4MjEsQQ0KMjAyNC0wNSwiQ2FsZ2FyeSwgQWxiZXJ0YSIsMjk3MzgxMixBDQoyMDI0LTA1LEFsYmVydGEsOTM5NTE0NCxBDQoyMDI0LTA1LENhbmFkYSw3Mzk0OTU0NSxBDQoyMDI0LTA2LCJFZG1vbnRvbiwgQWxiZXJ0YSIsMzAzNTk4OSxBDQoyMDI0LTA2LCJDYWxnYXJ5LCBBbGJlcnRhIiwyNzg3ODIzLEENCjIwMjQtMDYsQWxiZXJ0YSw4ODY2NzUxLEENCjIwMjQtMDYsQ2FuYWRhLDY5NDYyNDMxLEENCjIwMjQtMDcsIkVkbW9udG9uLCBBbGJlcnRhIiwzMTk4NTk5LEENCjIwMjQtMDcsIkNhbGdhcnksIEFsYmVydGEiLDI4NzU3NDYsQQ0KMjAyNC0wNyxBbGJlcnRhLDkxNTE2NjMsQQ0KMjAyNC0wNyxDYW5hZGEsNzA4NjQzMzksQQ0KMjAyNC0wOCwiRWRtb250b24sIEFsYmVydGEiLDMxNDg1MDAsQQ0KMjAyNC0wOCwiQ2FsZ2FyeSwgQWxiZXJ0YSIsMjg2MDk3MyxBDQoyMDI0LTA4LEFsYmVydGEsOTAwMzMzMyxBDQoyMDI0LTA4LENhbmFkYSw3MDgxNzExMyxBDQoyMDI0LTA5LCJFZG1vbnRvbiwgQWxiZXJ0YSIsMzAwMjUwNCxBDQoyMDI0LTA5LCJDYWxnYXJ5LCBBbGJlcnRhIiwyNzE3MTIxLEENCjIwMjQtMDksQWxiZXJ0YSw4NTg3NjUzLEENCjIwMjQtMDksQ2FuYWRhLDY2NjQ1MDkxLEENCjIwMjQtMTAsIkVkbW9udG9uLCBBbGJlcnRhIiwzMTk4NzU3LEENCjIwMjQtMTAsIkNhbGdhcnksIEFsYmVydGEiLDI5NzY4MjQsQQ0KMjAyNC0xMCxBbGJlcnRhLDkzMDA1NDEsQQ0KMjAyNC0xMCxDYW5hZGEsNzE3NTgwNjEsQQ0KMjAyNC0xMSwiRWRtb250b24sIEFsYmVydGEiLDMwMDQ3ODQsQQ0KMjAyNC0xMSwiQ2FsZ2FyeSwgQWxiZXJ0YSIsMjkxNjIzMixBDQoyMDI0LTExLEFsYmVydGEsODkyNDQzMyxBDQoyMDI0LTExLENhbmFkYSw3MTg1Mzk4NixBDQoyMDI0LTEyLCJFZG1vbnRvbiwgQWxiZXJ0YSIsMzA4NTEyMSxBDQoyMDI0LTEyLCJDYWxnYXJ5LCBBbGJlcnRhIiwyOTc2ODkxLEENCjIwMjQtMTIsQWxiZXJ0YSw5MTg2NTcxLEENCjIwMjQtMTIsQ2FuYWRhLDczMDIyODg3LEENCjIwMjUtMDEsIkVkbW9udG9uLCBBbGJlcnRhIiwyNjk1MTI1LEENCjIwMjUtMDEsIkNhbGdhcnksIEFsYmVydGEiLDIzODM1OTksQQ0KMjAyNS0wMSxBbGJlcnRhLDc3MDg1NzEsQQ0KMjAyNS0wMSxDYW5hZGEsNjA1MjU4MDgsQQ0KMjAyNS0wMiwiRWRtb250b24sIEFsYmVydGEiLDIzNjgxNjMsQQ0KMjAyNS0wMiwiQ2FsZ2FyeSwgQWxiZXJ0YSIsMjMxMTMzNixBDQoyMDI1LTAyLEFsYmVydGEsNzI1MDAxMixBDQoyMDI1LTAyLENhbmFkYSw1NzMxMTgyNyxBDQoyMDI1LTAzLCJFZG1vbnRvbiwgQWxiZXJ0YSIsMjk0MjM2MyxBDQoyMDI1LTAzLCJDYWxnYXJ5LCBBbGJlcnRhIiwyNzY1NjAyLEENCjIwMjUtMDMsQWxiZXJ0YSw4NzAzODk4LEENCjIwMjUtMDMsQ2FuYWRhLDY3Mzk5OTA5LEENCjIwMjUtMDQsIkVkbW9udG9uLCBBbGJlcnRhIiwyODM4Nzk4LEENCjIwMjUtMDQsIkNhbGdhcnksIEFsYmVydGEiLDI3NTUxMzEsQQ0KMjAyNS0wNCxBbGJlcnRhLDg2MjY5ODMsQQ0KMjAyNS0wNCxDYW5hZGEsNzExODE3ODcsQQ0KMjAyNS0wNSwiRWRtb250b24sIEFsYmVydGEiLDMzNTk3MTIsQQ0KMjAyNS0wNSwiQ2FsZ2FyeSwgQWxiZXJ0YSIsMzA3ODY0MixBDQoyMDI1LTA1LEFsYmVydGEsOTgwNzgwMCxBDQoyMDI1LTA1LENhbmFkYSw3NjgzMTg0OCxBDQoyMDI1LTA2LCJFZG1vbnRvbiwgQWxiZXJ0YSIsMzIxNjAyNCxBDQoyMDI1LTA2LCJDYWxnYXJ5LCBBbGJlcnRhIiwyODkwMDI5LEENCjIwMjUtMDYsQWxiZXJ0YSw5MzA1NzE3LEENCjIwMjUtMDYsQ2FuYWRhLDczMTc0NzM2LEENCjIwMjUtMDcsIkVkbW9udG9uLCBBbGJlcnRhIiwzMTk5MTU0LEENCjIwMjUtMDcsIkNhbGdhcnksIEFsYmVydGEiLDI4NzMyNzQsQQ0KMjAyNS0wNyxBbGJlcnRhLDkzNDcxNTgsQQ0KMjAyNS0wNyxDYW5hZGEsNzQxMzQ1MTYsQQ0KMjAyNS0wOCwiRWRtb250b24sIEFsYmVydGEiLDMyMzYxMTYsQQ0KMjAyNS0wOCwiQ2FsZ2FyeSwgQWxiZXJ0YSIsMjg5NTEyNSxBDQoyMDI1LTA4LEFsYmVydGEsOTMwMzY5NyxBDQoyMDI1LTA4LENhbmFkYSw3MzA0NjY0MCxBDQoyMDI1LTA5LCJFZG1vbnRvbiwgQWxiZXJ0YSIsMjgyNjI3NixBDQoyMDI1LTA5LCJDYWxnYXJ5LCBBbGJlcnRhIiwyODQ2ODg5LEENCjIwMjUtMDksQWxiZXJ0YSw4NzUyMjQ5LEENCjIwMjUtMDksQ2FuYWRhLDY5NTYxNTA3LEENCjIwMjUtMTAsIkVkbW9udG9uLCBBbGJlcnRhIiwzMjEyOTY4LEENCjIwMjUtMTAsIkNhbGdhcnksIEFsYmVydGEiLDI5NTc3MTksQQ0KMjAyNS0xMCxBbGJlcnRhLDkzMTY5MTQsQQ0KMjAyNS0xMCxDYW5hZGEsNzMxMDE2MTUsQQ0KMjAyNS0xMSwiRWRtb250b24sIEFsYmVydGEiLDMyMjg3MzUsQQ0KMjAyNS0xMSwiQ2FsZ2FyeSwgQWxiZXJ0YSIsMjk3OTkxOCxBDQoyMDI1LTExLEFsYmVydGEsOTI4Mjg1MSxBDQoyMDI1LTExLENhbmFkYSw3Mjg0NTg3NCxBDQoyMDI1LTEyLCJFZG1vbnRvbiwgQWxiZXJ0YSIsMzIxMjM0OCxBDQoyMDI1LTEyLCJDYWxnYXJ5LCBBbGJlcnRhIiwzMDgzMzA4LEENCjIwMjUtMTIsQWxiZXJ0YSw5NDgzMzcyLEENCjIwMjUtMTIsQ2FuYWRhLDc0NTEzODAzLEENCjIwMjYtMDEsIkVkbW9udG9uLCBBbGJlcnRhIiwyODc5Njc5LEENCjIwMjYtMDEsIkNhbGdhcnksIEFsYmVydGEiLDI2MDI5NzMsQQ0KMjAyNi0wMSxBbGJlcnRhLDgyMDI5MTQsQQ0KMjAyNi0wMSxDYW5hZGEsNjE1ODM4NjAsQQ0KMjAyNi0wMiwiRWRtb250b24sIEFsYmVydGEiLDI3MDM2NDIsQQ0KMjAyNi0wMiwiQ2FsZ2FyeSwgQWxiZXJ0YSIsMjQ2MTQyNCxBDQoyMDI2LTAyLEFsYmVydGEsNzY0NjQ3NixBDQoyMDI2LTAyLENhbmFkYSw1OTcxNjI1MixBDQoyMDI2LTAzLCJFZG1vbnRvbiwgQWxiZXJ0YSIsMzI3NzUyNSxBDQoyMDI2LTAzLCJDYWxnYXJ5LCBBbGJlcnRhIiwyOTgwNjk1LEENCjIwMjYtMDMsQWxiZXJ0YSw5MzA4NzU0LEENCjIwMjYtMDMsQ2FuYWRhLDcwMDY3NzE1LEENCjIwMjYtMDQsIkVkbW9udG9uLCBBbGJlcnRhIiwzMzM0MDc3LEENCjIwMjYtMDQsIkNhbGdhcnksIEFsYmVydGEiLDI5ODExNjUsQQ0KMjAyNi0wNCxBbGJlcnRhLDkzNjU4MTcsQQ0KMjAyNi0wNCxDYW5hZGEsNzMzMzgzNzMsQQ0KMjAyNi0wNSwiRWRtb250b24sIEFsYmVydGEiLDM2NDAwNTMsQQ0KMjAyNi0wNSwiQ2FsZ2FyeSwgQWxiZXJ0YSIsMzMzMDkxMCxBDQoyMDI2LTA1LEFsYmVydGEsMTA1NzY0MDIsQQ0KMjAyNi0wNSxDYW5hZGEsNzk5Mjc0OTksQQ0KMjAyNi0wNiwiRWRtb250b24sIEFsYmVydGEiLDM1MzQ3NDYsQQ0KMjAyNi0wNiwiQ2FsZ2FyeSwgQWxiZXJ0YSIsMzE1MjAwNyxBDQoyMDI2LTA2LEFsYmVydGEsMTAxNjY2NTcsQQ0KMjAyNi0wNixDYW5hZGEsNzg0NzU4OTAsQQ0KMjAyNi0wNywiRWRtb250b24sIEFsYmVydGEiLDM1ODMxMjAsQQ0KMjAyNi0wNywiQ2FsZ2FyeSwgQWxiZXJ0YSIsMzEzMTY5MSxCDQoyMDI2LTA3LEFsYmVydGEsMTAyMzExMzUsQQ0KMjAyNi0wNyxDYW5hZGEsNzc4MTcyMzYsQQ0K", BinaryEncoding.Base64), [Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Dates = Table.TransformColumns(Headers, {{"month", each Date.FromText(_ & "-01", [Format="yyyy-MM-dd", Culture="en-CA"]), type date}}),
			    Types = Table.TransformColumnTypes(Dates, {{"geography", type text}, {"sales_cad_thousands", Int64.Type}, {"quality_status", type text}})
			in
			    Types
